---
- hosts: web
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
    
    - name: Iniciar servicio Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copiar archivo HTML a Apache
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
