name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Fix permissions
      run: chmod +x $(npm bin)/jest || true

    - name: Run tests
      run: npm test
